spring:
  application:
      name: shopapp
  datasource:
    url: 'jdbc:mysql://localhost:3306/shopapp?createDatabaseIfNotExist=true'
    username: root
    password: 123456789
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

file:
  upload-dir: 'uploads\'

server:
  port: 8080
  servlet:
    context-path: /api/v1

